# Generated by Django 3.2.2 on 2021-05-12 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20210512_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 16, 52, 56, 41510, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 16, 52, 56, 41510, tzinfo=utc)),
        ),
    ]
