# Generated by Django 3.2.2 on 2021-05-13 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20210512_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='extra_name',
            field=models.CharField(default='null', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 6, 27, 990229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 6, 27, 990229, tzinfo=utc)),
        ),
    ]
