# Generated by Django 3.2.2 on 2021-05-13 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_auto_20210513_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 14, 59, 927895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 14, 59, 927895, tzinfo=utc)),
        ),
    ]
