# Generated by Django 3.2.2 on 2021-05-13 02:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_auto_20210513_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 51, 59, 713181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 51, 59, 713181, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 51, 59, 713181, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2021, 5, 13, 2, 51, 59, 713181, tzinfo=utc))),
                ('test_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person', to='hrm.person')),
            ],
        ),
    ]
