# Generated by Django 3.2.3 on 2021-05-13 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_auto_20210513_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelx',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 9, 13, 35, 498041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modelx',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 9, 13, 35, 498069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 9, 13, 35, 497437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 9, 13, 35, 497477, tzinfo=utc)),
        ),
    ]
